name: Daily Story at 4 PM UTC

on:
  schedule:
    - cron: "0 16 * * *"  # 4 PM UTC
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode (no posting to IG/FB)"
        required: false
        default: "false"

jobs:
  run-daily-story:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install boto3 moviepy==2.0.0.dev2 opencv-python numpy Pillow python-dotenv requests

      - name: Run main_story.py with or without dry-run
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          USER_ACCESS_TOKEN: ${{ secrets.USER_ACCESS_TOKEN }}
          IG_ID: ${{ secrets.IG_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            echo "Running in DRY RUN mode"
            python main_story.py --dry-run
          else
            echo "Running normally"
            python auto_post/main_story.py
          fi
