name: Daily Post at 2 PM UTC
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode (no posting to IG/FB)"
        required: false
        default: "false"

jobs:
  run-daily-post:
    runs-on: ubuntu-latest
    # 1. Allow write access so the job can push commits back to the repo
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensures credentials are saved

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install openai boto3 requests

      - name: Run main.py with or without dry-run
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          USER_ACCESS_TOKEN: ${{ secrets.USER_ACCESS_TOKEN }}
          IG_ID: ${{ secrets.IG_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            echo "Running in DRY RUN mode"
            python main.py --dry-run
          else
            echo "Running normally"
            python main.py
          fi

      - name: Commit and push updated url.json (if changed)
        # Expose GITHUB_TOKEN and configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add url.json
          git commit -m "Update url.json" || echo "No changes to commit"     
          git push
