name: Daily Post at 2 PM UTC
on:
  schedule:
    - cron: "0 14 * * *"  # Runs daily at 2 PM UTC
  workflow_dispatch:  # Allows manual trigger with optional dry-run
    inputs:
      dry_run:
        description: "Run in dry-run mode (no posting to IG/FB)"
        required: false
        default: "false"

jobs:
  run-daily-post:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install openai boto3 requests

      - name: Run main.py with or without dry-run
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          USER_ACCESS_TOKEN: ${{ secrets.USER_ACCESS_TOKEN }}
          IG_ID: ${{ secrets.IG_ID }}
        run: |
          if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            echo "Running in DRY RUN mode"
            python main.py --dry-run
          else
            echo "Running normally"
            python main.py
          fi

      - name: Commit and push updated url.json (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add url.json
          git commit -m "Update url.json" || echo "No changes to commit"
          git pull --rebase origin main
          git push
